[package]
name = "libreddit"
description = " Alternative private front-end to Reddit"
license = "AGPL-3.0"
repository = "https://github.com/spikecodes/libreddit"
version = "0.2.4"
authors = ["spikecodes <19519553+spikecodes@users.noreply.github.com>"]
edition = "2018"

[features]
default = ["proxy"]
proxy = ["actix-web/rustls", "base64"]

[dependencies]
base64 = { version = "0.13.0", optional = true }
actix-web = "3.2.0"
reqwest = { version = "0.10", default_features = false, features = ["rustls-tls"] }
askama = "0.8.0"
serde = "1.0.117"
serde_json = "1.0"
chrono = "0.4.19"
async-recursion = "0.3.1"
url = "2.2.0"