name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Packages
        uses: Swatinem/rust-cache@v1.0.1

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v2.2.1
        name: Upload a Build Artifact
        with:
          name: libreddit
          path: target/release/libreddit
          
      - name: Add to tree
        run: |
          mv -n target/release/libreddit ../../libreddit
          git config user.name dothq-robot
          git config user.email ghbot@dothq.co
          git add .
          git commit -m "Update libreddit"
          git push origin master
